### PR TITLE
Index dashboard

### PR DESCRIPTION
**Pull request by gdimit01**
Just the main index page created with header

### CODE REVIEW

**Comment by gdimit01** [comment]
For you to checkout and see

**Comment by jamesrcraigie** [comment]
I've noticed that some of the pictures you have added are not for candle store. Please remove these photos from the repository.

**Comment by jamesrcraigie** [comment]
Code looks good though!

**Comment by gdimit01** [comment]
> I've noticed that some of the pictures you have added are not for candle store. Please remove these photos from the repository.

Ah good spot. Shall do, cheers!

EDIT: I just updated it. I will just have to continue with it to properly display the product images on the ProductCard as it has the default react settings on it for now

**Pull request merged**
